changelog-seen = 2

[build]
target = ["wasm32-wasmer-wasi", "wasm64-wasmer-wasi", "wasix32-unknown-linux-gnu", "wasix64-unknown-linux-gnu"]
extended = true
tools = [ "clippy", "rustfmt" ]
configure-args = []

[rust]
lld = true
llvm-tools = true

[llvm]
download-ci-llvm = false

[target.wasm32-wasmer-wasi]
wasi-root = "../wasix-libc/sysroot32"

[target.wasix32-unknown-linux-gnu]
wasi-root = "../wasix-libc/sysroot32"

[target.wasm64-wasmer-wasi]
wasi-root = "../wasix-libc/sysroot64"

[target.wasix64-unknown-linux-gnu]
wasi-root = "../wasix-libc/sysroot64"
